name: build executables

on:
  push:
    tags:
      - "v*"

jobs:
  windows-build:
    runs-on: windows-latest
    steps:
      - name: Checkout commit
        uses: actions/checkout@master

      - name: Set up Python 3.9
        uses: actions/setup-python@master
        with: { python-version: 3.9 }

      - name: Upgrade pip
        run: python -m pip install --upgrade pip PyInstaller

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: build
        run: pyinstaller main.py --onefile

      - name: upload
        uses: actions/upload-artifact@v1
        with:
          name: Salmonia-windows
          path: dist/Salmonia.exe

  # macOS-build:
  #   runs-on: macOS-latest
  #   steps:
  #     - name: Checkout commit
  #       uses: actions/checkout@master

  #     - name: Set up Python 3.9
  #       uses: actions/setup-python@master
  #       with: { python-version: 3.9 }

  #     - name: Upgrade pip
  #       run: python -m pip install --upgrade pip PyInstaller

  #     - name: Install requirements
  #       run: pip install -r requirements.txt

  #     - name: build
  #       run: pyinstaller -F Salmonia.py

  #     - name: upload
  #       uses: actions/upload-artifact@v1
  #       with:
  #         name: Salmonia-macos
  #         path: dist/Salmonia

  # ubuntu-build:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout commit
  #       uses: actions/checkout@master

  #     - name: Set up Python 3.9
  #       uses: actions/setup-python@master
  #       with: { python-version: 3.9 }

  #     - name: Upgrade pip
  #       run: python -m pip install --upgrade pip PyInstaller

  #     - name: Install requirements
  #       run: pip install -r requirements.txt

  #     - name: build
  #       run: pyinstaller -F Salmonia.py

  #     - name: upload
  #       uses: actions/upload-artifact@v1
  #       with:
  #         name: Salmonia-linux
  #         path: dist/Salmonia

  release:
    # needs: [ubuntu-build, macOS-build, windows-build]
    # runs-on: ubuntu-latest
    needs: [windows-build]
    runs-on: ubuntu-latest

    steps:
      # - name: Download Linux
      #   uses: actions/download-artifact@v1
      #   with:
      #     name: Salmonia-linux

      # - name: Download Mac
      #   uses: actions/download-artifact@v1
      #   with:
      #     name: Salmonia-macos

      - name: Download Windows
        uses: actions/download-artifact@v1
        with:
          name: Salmonia-windows

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Zip
        # run: |
        #   tar -C Salmonia-macos -pczvf Salmonia-macos.tar.gz Salmonia
        #   tar -C Salmonia-linux -pczvf Salmonia-linux.tar.gz Salmonia
        #   zip --junk-paths Salmonia-windows ./Salmonia-windows/Salmonia.exe
        run: zip --junk-paths Salmonia-windows ./Salmonia-windows/Salmonia.exe
      # - name: Append Binary
      #   uses: actions/upload-release-asset@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     upload_url: ${{ steps.create_release.outputs.upload_url }}
      #     asset_path: ./Salmonia-macos.tar.gz
      #     asset_name: Salmonia-macos.tar.gz
      #     asset_content_type: application/gzip

      # - name: Append Binary
      #   uses: actions/upload-release-asset@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     upload_url: ${{ steps.create_release.outputs.upload_url }}
      #     asset_path: ./Salmonia-linux.tar.gz
      #     asset_name: Salmonia-linux.tar.gz
      #     asset_content_type: application/gzip

      - name: Append Binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./Salmonia-windows.zip
          asset_name: Salmonia-windows.zip
          asset_content_type: application/zip
